name: Baidu Tieba Auto Sign

on:
  workflow_dispatch:
  schedule:
  - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Auto Sign
      env:
        BDUSS_1: ${{ secrets.BDUSS_1 }}
        STOKEN_1: ${{ secrets.STOKEN_1 }}
      run: |
        pip install --user beautifulsoup4
        python tb_sign.py "$BDUSS_1:$STOKEN_1"
        
        
